# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'save.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SaveDialog(object):
    def setupUi(self, SaveDialog):
        SaveDialog.setObjectName("SaveDialog")
        SaveDialog.resize(400, 122)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        SaveDialog.setFont(font)
        self.verticalLayout = QtWidgets.QVBoxLayout(SaveDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lblOType = QtWidgets.QLabel(SaveDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblOType.sizePolicy().hasHeightForWidth())
        self.lblOType.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.lblOType.setFont(font)
        self.lblOType.setFrameShape(QtWidgets.QFrame.Box)
        self.lblOType.setObjectName("lblOType")
        self.horizontalLayout.addWidget(self.lblOType)
        self.cbOType = QtWidgets.QComboBox(SaveDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbOType.sizePolicy().hasHeightForWidth())
        self.cbOType.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.cbOType.setFont(font)
        self.cbOType.setObjectName("cbOType")
        self.horizontalLayout.addWidget(self.cbOType)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lblOutput = QtWidgets.QLabel(SaveDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblOutput.sizePolicy().hasHeightForWidth())
        self.lblOutput.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.lblOutput.setFont(font)
        self.lblOutput.setFrameShape(QtWidgets.QFrame.Box)
        self.lblOutput.setObjectName("lblOutput")
        self.horizontalLayout_2.addWidget(self.lblOutput)
        self.cbOutput = QtWidgets.QComboBox(SaveDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbOutput.sizePolicy().hasHeightForWidth())
        self.cbOutput.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.cbOutput.setFont(font)
        self.cbOutput.setObjectName("cbOutput")
        self.horizontalLayout_2.addWidget(self.cbOutput)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.btSave = QtWidgets.QPushButton(SaveDialog)
        self.btSave.setObjectName("btSave")
        self.horizontalLayout_7.addWidget(self.btSave)
        self.btCancel = QtWidgets.QPushButton(SaveDialog)
        self.btCancel.setObjectName("btCancel")
        self.horizontalLayout_7.addWidget(self.btCancel)
        self.verticalLayout.addLayout(self.horizontalLayout_7)

        self.retranslateUi(SaveDialog)
        QtCore.QMetaObject.connectSlotsByName(SaveDialog)

    def retranslateUi(self, SaveDialog):
        _translate = QtCore.QCoreApplication.translate
        SaveDialog.setWindowTitle(_translate("SaveDialog", "Сохранение"))
        self.lblOType.setText(_translate("SaveDialog", "Вывести по:"))
        self.lblOutput.setText(_translate("SaveDialog", "Регион:"))
        self.btSave.setText(_translate("SaveDialog", "Сохранить"))
        self.btCancel.setText(_translate("SaveDialog", "Отмена"))
